name: Weekly Stability Test
on:
  workflow_dispatch: # run on request (no need for PR)
  schedule:
    # every 7PM on Sunday
    - cron: "0 19 * * 0"

defaults:
  run:
    shell: bash

jobs:
  weekly_stability_test:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-11', 'ubuntu-20.04', 'windows-2019']
        python-version: ['3.8']
    name: stability test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Installing python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install tox
      - name: Stability testing
        run: tox -vv -e weekly-test -- --minutes 30
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: .tox/stability_test_report.html
  call-notify-to-teams:
    needs: [weekly_stability_test]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: ./.github/workflows/notify_teams.yml
    secrets: inherit
